-- Bronze: lo más cercano posible a la fuente. Sin limpieza; solo metadata de origen y carga.
select
    vendorid,
    tpep_pickup_datetime,
    tpep_dropoff_datetime,
    passenger_count,
    trip_distance,
    ratecodeid,
    store_and_fwd_flag,
    pulocationid,
    dolocationid,
    payment_type,
    fare_amount,
    extra,
    mta_tax,
    tip_amount,
    tolls_amount,
    improvement_surcharge,
    total_amount,
    congestion_surcharge,
    airport_fee,
    cbd_congestion_fee,
    request_source,
    _source_file,
    _source_period,
    _loaded_at
from {{ source('raw', 'yellow_tripdata') }}
