name: nyc_taxi
version: "1.0.0"
profile: nyc_taxi

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
clean-targets: ["target", "dbt_packages"]

models:
  nyc_taxi:
    bronze:
      +schema: BRONZE
      +materialized: view
    silver:
      +schema: SILVER
      +materialized: table
    gold:
      +schema: GOLD
      +materialized: table

seeds:
  nyc_taxi:
    +schema: SILVER
