-- Ejecutar completo en Snowsight como ACCOUNTADMIN. Es idempotente.
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS NYC_PIPELINE_ROLE;
GRANT ROLE NYC_PIPELINE_ROLE TO ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS NYC_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
GRANT USAGE, OPERATE ON WAREHOUSE NYC_WH TO ROLE NYC_PIPELINE_ROLE;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE NYC_PIPELINE_ROLE;

CREATE USER IF NOT EXISTS NYC_PIPELINE
  TYPE = SERVICE
  DEFAULT_ROLE = NYC_PIPELINE_ROLE
  DEFAULT_WAREHOUSE = NYC_WH;
GRANT ROLE NYC_PIPELINE_ROLE TO USER NYC_PIPELINE;

-- Los objetos se crean con el rol del pipeline para que sea su dueño.
USE ROLE NYC_PIPELINE_ROLE;

CREATE DATABASE IF NOT EXISTS NYC_TAXI;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.RAW;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.BRONZE;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.SILVER;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.GOLD;

CREATE FILE FORMAT IF NOT EXISTS NYC_TAXI.RAW.PARQUET_FF
  TYPE = PARQUET
  USE_LOGICAL_TYPE = TRUE;

CREATE STAGE IF NOT EXISTS NYC_TAXI.RAW.TLC_STAGE
  FILE_FORMAT = NYC_TAXI.RAW.PARQUET_FF;

-- Nombres de la fuente; tipos amplios para absorber cambios de tipo entre meses.
CREATE TABLE IF NOT EXISTS NYC_TAXI.RAW.YELLOW_TRIPDATA (
  VENDORID              NUMBER(38,0),
  TPEP_PICKUP_DATETIME  TIMESTAMP_NTZ,
  TPEP_DROPOFF_DATETIME TIMESTAMP_NTZ,
  PASSENGER_COUNT       FLOAT,
  TRIP_DISTANCE         FLOAT,
  RATECODEID            FLOAT,
  STORE_AND_FWD_FLAG    VARCHAR,
  PULOCATIONID          NUMBER(38,0),
  DOLOCATIONID          NUMBER(38,0),
  PAYMENT_TYPE          NUMBER(38,0),
  FARE_AMOUNT           FLOAT,
  EXTRA                 FLOAT,
  MTA_TAX               FLOAT,
  TIP_AMOUNT            FLOAT,
  TOLLS_AMOUNT          FLOAT,
  IMPROVEMENT_SURCHARGE FLOAT,
  TOTAL_AMOUNT          FLOAT,
  CONGESTION_SURCHARGE  FLOAT,
  AIRPORT_FEE           FLOAT,
  CBD_CONGESTION_FEE    FLOAT,
  REQUEST_SOURCE        VARCHAR,
  _SOURCE_FILE          VARCHAR,
  _SOURCE_PERIOD        VARCHAR(7),
  _LOADED_AT            TIMESTAMP_LTZ
);
